In [3]:
!pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [6]:
url = "https://raw.githubusercontent.com/myoh0623/dataset/main/wine.data"

In [8]:
iris = pd.read_csv(url)

In [9]:
iris

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [4]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [6]:
raw_data

{'regiment': ['Nighthawks',
  'Nighthawks',
  'Nighthawks',
  'Nighthawks',
  'Dragoons',
  'Dragoons',
  'Dragoons',
  'Dragoons',
  'Scouts',
  'Scouts',
  'Scouts',
  'Scouts'],
 'company': ['1st',
  '1st',
  '2nd',
  '2nd',
  '1st',
  '1st',
  '2nd',
  '2nd',
  '1st',
  '1st',
  '2nd',
  '2nd'],
 'name': ['Miller',
  'Jacobson',
  'Ali',
  'Milner',
  'Cooze',
  'Jacon',
  'Ryaner',
  'Sone',
  'Sloan',
  'Piger',
  'Riani',
  'Ali'],
 'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
 'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [22]:
regiment = pd.DataFrame(raw_data)

In [24]:
print(regiment)

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70


In [26]:
nighthawks = regiment[regiment['regiment'] == 'Nighthawks']

# 평균 preTestScore 계산
average_preTestScore = nighthawks['preTestScore'].mean()

# 결과 출력
print("Nighthawks regiment의 평균 preTestScore는:", average_preTestScore)

Nighthawks regiment의 평균 preTestScore는: 15.25


In [36]:
a =pd.read_csv(https://raw.githubusercontent.com/myoh0623/dataset/main/student-mat.csv)

SyntaxError: invalid syntax (647762783.py, line 1)

In [32]:
a

'https://raw.githubusercontent.com/myoh0623/dataset/main/student-mat.csv'

In [38]:
a = "https://raw.githubusercontent.com/myoh0623/dataset/main/US_Crime_Rates_1960_2014.csv"

In [40]:
df = pd.read_csv(a)

In [44]:
df.head(3)

Year  Population    Total  Violent  Property  Murder  Forcible_Rape  \
0  1960   179323175  3384200   288460   3095700    9110          17190   
1  1961   182992000  3488000   289390   3198600    8740          17220   
2  1962   185771000  3752200   301510   3450700    8530          17550   

   Robbery  Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft  
0   107840              154320    912100        1855400         328200  
1   106670              156760    949600        1913000         336000  
2   110860              164570    994300        2089600         366800

In [48]:
crime.dtypes

NameError: name 'crime' is not defined

In [6]:
n = 10 
arr_1 = np.full((n,n), 0)
for i in range(n):
    for j in range(n):
        if i >= j :
            arr_1[i, j] =1 
print(arr_1)

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:
arr_1[1,0]

1

In [10]:
arr_1[2,0]

1

In [12]:
arr_1[8,0]

1

In [14]:
arr_1[8, 8]

1

In [16]:
np.tril?

Signature:       np.tril(m, k=0)
Call signature:  np.tril(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function tril at 0x000001B82DA37E20>
File:            c:\users\qkskf\anaconda3\lib\site-packages\numpy\lib\twodim_base.py
Docstring:      
Lower triangle of an array.

Return a copy of an array with elements above the `k`-th diagonal zeroed.
For arrays with ``ndim`` exceeding 2, `tril` will apply to the final two
axes.

Parameters
----------
m : array_like, shape (..., M, N)
    Input array.
k : int, optional
    Diagonal above which to zero elements.  `k = 0` (the default) is the
    main diagonal, `k < 0` is below it and `k > 0` is above.

Returns
-------
tril : ndarray, shape (..., M, N)
    Lower triangle of `m`, of same shape and data-type as `m`.

See Also
--------
triu : same thing, only for the upper triangle

Examples
--------
>>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
  

In [18]:
arr_1.shape

(10, 10)

In [20]:
arr_1.sum(0)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [24]:
arr_1.sum(1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])